name: cute_weather_v2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dotted_line: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.6
  provider: ^6.0.1
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true
