name: cute_weather_v2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dotted_line: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.6
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  location: ^4.2.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_app_name:
  name: "Cute Weather"

flutter:
  assets:
    - assets/
    - assets/translations/
  generate: true
  uses-material-design: true
